import ChessKit
import SwiftUI

// 16x16 pixel silhouettes. '#' = piece body, anything else = transparent.
// Outline is computed at render time: any body pixel adjacent to a
// transparent pixel becomes an outline pixel.
enum PieceShape {
    static let king = """
        .......##.......
        .......##.......
        .....######.....
        .......##.......
        ......####......
        .....######.....
        ....########....
        ....########....
        ...##########...
        ...##########...
        ...##########...
        ....########....
        ....########....
        ..############..
        .##############.
        ################
        """

    static let queen = """
        .#....##....#...
        .#.#.####.#.#...
        .##.######.##...
        .##########.....
        ..########......
        ...######.......
        ...######.......
        ..########......
        ..########......
        .##########.....
        .##########.....
        ..########......
        ...######.......
        ..########......
        .##########.....
        ################
        """

    static let rook = """
        ................
        .##.##.##.##.##.
        .##############.
        .##############.
        ...##########...
        ...##########...
        ...##########...
        ...##########...
        ...##########...
        ...##########...
        ...##########...
        ...##########...
        ...##########...
        .##############.
        ################
        ################
        """

    static let bishop = """
        ........#.......
        .......###......
        .......###......
        ......#####.....
        ......##.##.....
        ......#####.....
        .....#######....
        .....#######....
        ....#########...
        ....#########...
        ....#########...
        .....#######....
        ......#####.....
        .....#######....
        ....#########...
        ################
        """

    static let knight = """
        ................
        .......####.....
        ......######....
        .....########...
        ....##.######...
        ...####.#####...
        ..#########.##..
        .##########.....
        .##########.....
        ..#########.....
        ...########.....
        ....########....
        ....########....
        ...##########...
        ..############..
        ################
        """

    static let pawn = """
        ................
        ................
        ......####......
        .....######.....
        .....##..##.....
        .....######.....
        ......####......
        ......####......
        .....######.....
        ....########....
        ....########....
        ...##########...
        ...##########...
        ..############..
        .##############.
        ################
        """
}

struct PieceSprite: View {
    let piece: Piece

    var body: some View {
        Canvas { context, size in
            let rows = Self.parse(Self.shape(for: piece.kind))
            let gridSize = max(rows.count, rows.map(\.count).max() ?? 0)
            let pixel = min(size.width, size.height) / CGFloat(gridSize)

            let bodyColor: Color = piece.color == .white ? .white : .black
            let outlineColor: Color = .black

            for y in 0..<rows.count {
                for x in 0..<rows[y].count {
                    guard rows[y][x] else { continue }
                    let color = isOutline(x: x, y: y, in: rows) ? outlineColor : bodyColor
                    let rect = CGRect(
                        x: CGFloat(x) * pixel,
                        y: CGFloat(y) * pixel,
                        width: pixel + 0.5,
                        height: pixel + 0.5
                    )
                    context.fill(Path(rect), with: .color(color))
                }
            }
        }
        .aspectRatio(1, contentMode: .fit)
    }

    private static func shape(for kind: Piece.Kind) -> String {
        switch kind {
        case .king:   PieceShape.king
        case .queen:  PieceShape.queen
        case .rook:   PieceShape.rook
        case .bishop: PieceShape.bishop
        case .knight: PieceShape.knight
        case .pawn:   PieceShape.pawn
        }
    }

    private static func parse(_ shape: String) -> [[Bool]] {
        shape.split(separator: "\n").map { line in
            line.trimmingCharacters(in: .whitespaces).map { $0 == "#" }
        }
    }

    private func isOutline(x: Int, y: Int, in rows: [[Bool]]) -> Bool {
        for dy in -1...1 {
            for dx in -1...1 where dx != 0 || dy != 0 {
                let nx = x + dx, ny = y + dy
                if ny < 0 || ny >= rows.count {
                    return true
                }
                if nx < 0 || nx >= rows[ny].count {
                    return true
                }
                if !rows[ny][nx] {
                    return true
                }
            }
        }
        return false
    }
}
